"""Pydantic schemas for API request/response."""
from datetime import datetime
from typing import Any, List, Optional

from pydantic import BaseModel, Field


class ApplianceCreate(BaseModel):
    # external_id is optional and normally autogenerated by the backend.
    external_id: Optional[str] = Field(None, min_length=1, max_length=64)
    name: str = Field(..., min_length=1, max_length=255)
    priority: int = Field(1, ge=1, le=3)
    rated_watts: float = Field(..., gt=0)
    schedule_prefs: Optional[str] = None
    relay_topic: Optional[str] = None


class ApplianceUpdate(BaseModel):
    name: Optional[str] = Field(None, min_length=1, max_length=255)
    priority: Optional[int] = Field(None, ge=1, le=3)
    rated_watts: Optional[float] = Field(None, gt=0)
    schedule_prefs: Optional[str] = None
    relay_topic: Optional[str] = None
    is_on: Optional[bool] = None


class ApplianceOut(BaseModel):
    id: int
    external_id: str
    name: str
    priority: int
    rated_watts: float
    schedule_prefs: Optional[str] = None
    relay_topic: Optional[str] = None
    is_on: bool

    class Config:
        from_attributes = True


class PvSnapshot(BaseModel):
    power_kw: float
    voltage: float
    current_a: float
    timestamp: datetime


class BatterySnapshot(BaseModel):
    soc_percent: float
    voltage: float
    current_a: float
    timestamp: datetime


class LoadSnapshot(BaseModel):
    appliance_id: str
    name: str
    power_kw: float
    state: str


class StatusOut(BaseModel):
    timestamp: datetime
    pv: PvSnapshot
    battery: BatterySnapshot
    loads: List[LoadSnapshot]
    total_load_kw: float
    simulated: bool = True


class ForecastSeries(BaseModel):
    """Placeholder for LSTM forecast output."""
    timestamps: List[str]
    generation_kw: List[float]
    consumption_kw: List[float]


class ForecastOut(BaseModel):
    generated_at: datetime
    horizon_hours: int
    series: Optional[ForecastSeries] = None
    message: Optional[str] = None


class ScheduleSlotOut(BaseModel):
    appliance_id: int
    appliance_name: str
    start_ts: datetime
    end_ts: datetime
    planned_state: str
    status: str


class ScheduleOut(BaseModel):
    generated_at: Optional[datetime] = None
    slots: List[ScheduleSlotOut] = []
    message: Optional[str] = "IEBA schedule not yet implemented."


class HistoryPoint(BaseModel):
    timestamp: datetime
    power_kw: Optional[float] = None
    soc_percent: Optional[float] = None
    total_load_kw: Optional[float] = None


class StatusHistoryOut(BaseModel):
    """Time-series of PV, battery SOC, and total load for charts and LSTM export."""
    points: List[HistoryPoint]
    hours: int


class ModelCheckpointInfo(BaseModel):
    path: str
    seq_len: int
    feat_dim: int
    hidden: int
    feature_names: List[str]
    validation_smape: Optional[float] = None
    validation_mape_masked: Optional[float] = None
    validation_mae: Optional[float] = None
    validation_mape_legacy: Optional[float] = None


class ModelMonitorOut(BaseModel):
    """LSTM forecast pipeline status for the Model Monitor UI."""
    torch_available: bool
    gen_path: str
    load_path: str
    gen_file_exists: bool
    load_file_exists: bool
    models_load_ok: bool
    gen: Optional[ModelCheckpointInfo] = None
    load: Optional[ModelCheckpointInfo] = None
    errors: List[str] = []
    seed_source: str = "synthetic"
    ieba_uses_simulated_forecast: bool = True
    lstm_forecast_active: bool = False
    forecast_message: str = ""
    inference_ms: Optional[float] = None
    model_series: Optional[ForecastSeries] = None
    simulated_series: Optional[ForecastSeries] = None
    # Validation metrics from training (when checkpoint includes them)
    # Live metrics: model vs actual from DB history (when LSTM active and history available)
    live_smape_gen: Optional[float] = None
    live_smape_load: Optional[float] = None
    live_mape_masked_gen: Optional[float] = None
    live_mape_masked_load: Optional[float] = None
    live_mae_gen: Optional[float] = None
    live_mae_load: Optional[float] = None
    live_metrics_hours: Optional[int] = None
